// app/layout.js
import "@fontsource/inter"; // Defaults to weight 400
import "@fontsource/inter/600.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Inter } from 'next/font/google'
import NavBar from '../components/NavBar';


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'SmartLLM',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en" >
      <body  style={{fontFamily: 'Inter, sans-serif',}} className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}

